### ISSUE TITLE
bamToCountMuts should have more flexibility in outputs and better documentation for how to use.

### ISSUE THREAD

**Issue by KennedyLabUW** [KennedyLabUW/Duplex-Seq-Pipeline#1]
Putting this here for tracking purposes.

Currently, script outputs total mutation frequency, per gene mutations frequency, and per block mutation frequency. First, we should have the ability turn on (or off) which outputs happen at runtime. Solution could be have user turn on the level of output they want (i.e. invoke a `TOTAL`, `GENE`, `BLOCKS`, and `PERBLOCK`. The user could specify any combination of the four options they desired and it would get reported. Those not stated would be excluded. `TOTAL` would be as reported currently, `GENE` would mean all positions between chromstart and chromend,` BLOCKS` would mean the sum of all positions limited to the blocks and everything else excluded, `PERBLOCK` would be as currently reported. Default behavior would be `TOTAL`. Second, currently it's not clear if gene mutation frequency is the entire gene, meaning all nucleotides and mutations between chromstart and chromend, or if it's the sum of all the mutations limited to the blocks. Clarification would be handy.

**Comment by bkohrn** [comment]
I'm creating a branch specifically for development of this, as well as for other updates to the countmuts program.  See https://github.com/KennedyLabUW/Duplex-Seq-Pipeline/tree/countmuts_dev
